membrane-php/membrane-core

src/Filter/CreateObject/WithNamedArguments.php, src/Filter/Shape/Nest.php, src/Result/MessageSet.php, src/Result/Result.php, src/Validator/Logical/Not.php, src/Validator/String/Length.php, src/Validator/Utility/Chain.php, src/Validator/Utility/Indifferent.php, tests/Filter/CreateObject/FromArrayTest.php, tests/Filter/CreateObject/WithNamedArgumentsTest.php, tests/Filter/Shape/CollectTest.php, tests/Filter/Shape/NestTest.php, tests/Result/FieldnameTest.php, tests/Result/MessageSetTest.php, tests/Result/ResultTest.php, tests/Validator/Collection/IdenticalTest.php, tests/Validator/Logical/NotTest.php, tests/Validator/Object/RequiredFieldsTest.php, tests/Validator/String/LengthTest.php, tests/Validator/Utility/ChainTest.php, tests/Validator/Utility/FailsTest.php, tests/Validator/Utility/IndifferentTest.php, tests/Validator/Utility/PassesTest.php
Validator tests implemented,
Filter tests mostly implemented (WithNamedArguments incorrect arguments isn't validating the thrown message yet),
Result tests implemented
=> Validator and Filter Unit tests

src/Validator/String/DateString.php, src/Validator/String/Regex.php, tests/Validator/String/DateStringTest.php, tests/Validator/String/RegexTest.php
closes #6 
DateTime and Regex validators added
=> String Validators

.laminas-ci.json, composer.json, phpstan.neon, src/Membrane.php
PHPstan added to composer.json.
config file setup (phpstan.neon)
Level 0 passed with minimal corrections to src/Membrane
Level 1 requires changes to src/Processor/Field.php which may cause conflicts with PR #16.
=> PHPstan level 0

src/Attribute/Builder.php, src/Processor/AfterSet.php, src/Processor/BeforeSet.php, src/Processor/Collection.php, src/Processor/Field.php, src/Processor/Fieldset.php, tests/Processor/AfterSetTest.php, tests/Processor/BeforeSetTest.php, tests/Processor/CollectionTest.php, tests/Processor/FieldTest.php, tests/Processor/FieldsetTest.php
=> Processor tests

src/Validator/Utility/Not.php, tests/Validator/Utility/NotTest.php
Not Validator and its tests moved to Utility, Logical directory no longer needed.
=> Not Validator moved to Utility

docs/basics.md, docs/filters.md, docs/index.md, docs/processors.md, docs/result.md, docs/validators.md, mkdocs.yml
Basic level of documentation to get started from.
=> Basic Documentation

docs/builder.md, docs/filters.md, docs/index.md, docs/processors.md, docs/result.md, docs/validators.md, mkdocs.yml
- All Validators and Filters have at least one example.
- Builder has one extensive example (Building a Blog Post)
- php styling added to all php code blocks,
- text styling added to all output blocks and composer block
- few small tweaks to layout in other sections,
=> Filter|Validator|Builder Examples added to docs

src/Validator/Utility/AnyOf.php, tests/Validator/Utility/AnyOfTest.php
Making way for new OneOf validator to fit with OpenAPI
=> OneOf renamed to AnyOf

docs/validators.md, src/Validator/Type/IsArray.php, src/Validator/Type/IsFloat.php, src/Validator/Type/IsInt.php, src/Validator/Type/IsList.php, src/Validator/Type/IsNull.php, src/Validator/Type/IsString.php, tests/Validator/Type/IsArrayTest.php, tests/Validator/Type/IsBoolTest.php, tests/Validator/Type/IsFloatTest.php, tests/Validator/Type/IsIntTest.php, tests/Validator/Type/IsListTest.php, tests/Validator/Type/IsNullTest.php
`IsNull()` validator checks if `$value === null`
All Type validator messages updated for consistency
=> IsNull validator

docs/validators.md, src/Validator/Collection/Unique.php, tests/Validator/Collection/UniqueTest.php
Unique validator uses **strict comparison** to check if any items in an array are **identical**. Any identical items return invalid Results. Arrays with equal items are acceptable as long as they are not identical they will return valid.
=> Unique validator

docs/validators.md, example/register-user.php, src/Validator/Collection/Count.php, src/Validator/FieldSet/RequiredFields.php, tests/Attribute/BuilderTest.php, tests/Validator/Collection/CountTest.php, tests/Validator/FieldSet/RequiredFieldsTest.php, tests/fixtures/Attribute/ClassWithStringPropertyBeforeSet.php, tests/fixtures/Attribute/Docs/BlogPostFromNamedArguments.php, tests/fixtures/Attribute/Docs/BlogPostIsItAString.php, tests/fixtures/Attribute/Docs/BlogPostMakeItAString.php, tests/fixtures/Attribute/Docs/BlogPostMaxTags.php, tests/fixtures/Attribute/Docs/BlogPostRegexAndMaxLength.php, tests/fixtures/Attribute/Docs/BlogPostRequiredFields.php, tests/fixtures/Attribute/Docs/BlogPostWithAllOf.php
Count moved from Array/ to Collection/
Array/ became empty so has been removed.
Object/ renamed to FieldSet/
documentation updated to match.
=> Reorganisation

src/Filter/String/JsonDecode.php, tests/Filter/String/JsonDecodeTest.php
Several potential json decoding errors have not got test coverage, but cannot think of a way to produce error in php currently.
=> JsonDecode string filter added

src/Exception/InvalidProcessorArguments.php, src/Processor/Collection.php, src/Processor/FieldSet.php, tests/Processor/CollectionTest.php, tests/Processor/FieldsetTest.php
Processor exceptions covered for general use processors. Messages tweaked for consistency.
=> Exception: InvalidProcessorArguments added

src/Attribute/ClassWithAttributes.php, src/Attribute/FilterOrValidator.php, src/Attribute/Ignored.php, src/Attribute/OverrideProcessorType.php, src/Attribute/Placement.php, src/Attribute/SetFilterOrValidator.php, src/Attribute/Subtype.php, src/Builder/Builder.php, src/Builder/Specification.php, src/Exception/CannotProcessProperty.php, src/Filter/CreateObject/FromArray.php, src/Filter/CreateObject/WithNamedArguments.php, src/Filter/Shape/Collect.php, src/Filter/Shape/Nest.php, src/Processor/AfterSet.php, src/Processor/BeforeSet.php, src/Processor/ProcessorType.php, src/Validator/Collection/Identical.php, src/Validator/FieldSet/RequiredFields.php, src/Validator/String/Length.php, src/Validator/Type/IsArray.php, src/Validator/Type/IsList.php
Ensured all php files in `src/` have `declare(strict_types=1);`
=> Cleanup: missing strict declarations added

docs/result.md, src/Renderer/HumanReadable.php, src/Renderer/JsonFlat.php, src/Renderer/JsonNested.php, src/Renderer/Renderer.php, tests/Renderer/HumanReadableTest.php, tests/Renderer/JsonFlatTest.php, tests/Renderer/JsonNestedTest.php
**ADDS:**
- Renderer Interface implemented by:
- APIProblemFlat
- HumanReadable
- APIProblemNested
=> Result Renderer

src/Filter/String/AlphaNumeric.php, tests/Filter/String/AlphaNumericTest.php
Removes all characters that are not alphanumeric.
=> Add AlphaNumeric Filter

docs/filters.md, src/Exception/InvalidFilterArguments.php, src/Filter/String/Explode.php, tests/Filter/String/ExplodeTest.php
Adds a filter for exploding string values based on a string `$delimiter` constructor argument.
=> Add explode filter

tests/Filter/String/ExplodeTest.php
Test was missing #[Test] attribute so test was no being performed.
=> Add Test Attribute to Explode test

composer.json, phpunit.xml
close #111
Upgrades PHPUnit version to >= 10.1
Migrates configuration to remove deprecations.
=> Upgrade PHPUnit to ^10.1

src/Filter/Type/ToDateTime.php, src/Result/Message.php, src/Validator/Collection/Contained.php, src/Validator/DateTime/Range.php, src/Validator/DateTime/RangeDelta.php, tests/Filter/Type/ToDateTimeTest.php, tests/Validator/Collection/ContainedTest.php, tests/Validator/DateTime/RangeDeltaTest.php, tests/Validator/DateTime/RangeTest.php
Makes PHPStan happy.
For thoroughness we would probably want to test that all Filters|Processors|Validators return valid rendered messages.
=> Change Message vars to primitives or null

docs/validators.md, src/Validator/String/NumericString.php, tests/Validator/String/NumericStringTest.php
Basically an IsNumericString Validator. Only comes back valid for strings of integers and floats
=> Add IsNumericString Validator

src/OpenAPI/Builder/APIBuilder.php
(Subjectively) improves readability.
=> Refactor fromSchema switch statement to match statement

src/Filter/String/Implode.php, tests/Filter/String/ImplodeTest.php
Implodes arrays into string values
=> Add Implode Filter

src/OpenAPI/Builder/Objects.php, src/OpenAPI/Specification/Objects.php, tests/OpenAPI/Builder/ObjectsTest.php
=> Support minProperties & maxProperties

src/Filter/String/ToLowerCase.php, src/Filter/String/ToUpperCase.php, tests/Filter/String/ToLowerCaseTest.php, tests/Filter/String/ToUpperCaseTest.php
Add `ToUpperCase` and `ToLowerCase` String Filters.
=> String case filters

membrane.sh
Update Shell Script dependencies to 8.2
Slightly clearer naming conventions
=> Update Membrane Shell Script
