membrane-php/membrane-core

- src/Filter/Shape/Delete.php
- src/Filter/Shape/Pluck.php
- src/Filter/Shape/Rename.php
- src/Filter/Shape/Truncate.php
- tests/Filter/Shape/DeleteTest.php
- tests/Filter/Shape/PluckTest.php
- tests/Filter/Shape/RenameTest.php
- tests/Filter/Shape/TruncateTest.php
fixes #2 
Shape filters implemented
Truncate filter truncates lists only, making sure they are equal or below maxLength
Delete filter deletes a key from arrays only
Rename filter renames a key on arrays only
Pluck filter works on arrays only and achieves same result as example provided
> Shape filters

- src/Filter/Type/ToBool.php
- src/Filter/Type/ToDateTime.php
- src/Filter/Type/ToFloat.php
- src/Filter/Type/ToInt.php
- src/Filter/Type/ToList.php
- src/Filter/Type/ToString.php
- tests/Filter/Type/ToBoolTest.php
- tests/Filter/Type/ToDateTimeTest.php
- tests/Filter/Type/ToFloatTest.php
- tests/Filter/Type/ToIntTest.php
- tests/Filter/Type/ToListTest.php
- tests/Filter/Type/ToStringTest.php
resolves #3
String only converts null, scalar(int,float,string,bool) or objects with __toString
Bool(uses filter_var) only converts scalars. On top of this it only converts scalars that represent a boolean.
- ints: only 1 or 0, anything else fails
- floats: only 0.0 or 1.0, anything else fails
- strings: 'true', '1', 'on', 'yes' etc. work, anything else fails
- boolean: of course this was going to work
Int/Float converts null and scalars, if it's a string it has to be numeric or it fails.
List: converts arrays into lists, nothing else
DateTime converts strings into DateTimes or DateTimeImmutable
> Type filters

- docs/processors.md
- phpstan.neon
- src/Filter/Type/ToDateTime.php
- src/Filter/Type/ToString.php
- src/Processor/Collection.php
- src/Processor/FieldSet.php
- src/Validator/Array/Count.php
- src/Validator/Collection/Identical.php
- src/Validator/Object/RequiredFields.php
- src/Validator/String/DateString.php
- src/Validator/String/Length.php
- src/Validator/String/Regex.php
- src/Validator/Type/IsArray.php
- src/Validator/Type/IsList.php
- tests/Filter/Type/ToDateTimeTest.php
- tests/Filter/Type/ToIntTest.php
- tests/Processor/CollectionTest.php
- tests/Processor/FieldsetTest.php
- tests/Validator/Array/CountTest.php
- tests/Validator/Collection/IdenticalTest.php
- tests/Validator/Object/RequiredFieldsTest.php
- tests/Validator/String/DateStringTest.php
- tests/Validator/String/LengthTest.php
- tests/Validator/String/RegexTest.php
Filters/Validators required assertions on $value type being added at the beginning.
Where added, tests have been added to check functionality is works as intended.
Processors required existing assertions on $value type being moved and tweaked.
Where tweaked, tests have been tweaked to check new functionality works as intended.
> PHPStan level 9 reached

- docs/result.md
- src/Result/Message.php
- src/Validator/Array/Count.php
- tests/Result/MessageTest.php
- tests/Validator/Array/CountTest.php
Message has new method:
rendered(): string // returns the formatted message.
Also fixed a copy-paste error on Count.php when array exceeds maximum
> Message rendered method added

- src/Validator/Numeric/MultipleOf.php
- src/Validator/Numeric/Range.php
- tests/Validator/Numeric/MultipleOfTest.php
- tests/Validator/Numeric/RangeTest.php
`MultipleOf(float|int $factor)` Validator checks if given `$value` is a multiple of `$factor`
Currently using fmod to allow for floats since they're technically allowed:
> [multipleOf may be used with floating-point numbers, but in practice this can be unreliable due to the limited precision or floating point math. ](https://swagger.io/docs/specification/data-models/data-types/)
also added a similar is_numeric check to the Numeric/Range validator.
> MultipleOf Validator

- src/Validator/Collection/Unique.php
- tests/Validator/Collection/UniqueTest.php
Unique.php line 27-29 now covered by tests.
line 27-29 can potentially be removed without reducing functionality, however it does act as an early return for arrays that do not need unique checks. i.e. arrays of less than 2 items literally cannot have duplicates.
> unique tests 100% line coverage

- src/Filter/Type/ToNumber.php
- src/Validator/Type/IsNumber.php
- tests/Filter/Type/ToNumberTest.php
- tests/Validator/Type/IsNumberTest.php
Originally for OpenAPI type: number with unspecified format we used: 
```new AnyOf(new IsInt(), new IsFloat())```
This became more complicated when trying to implement a `$strict` boolean in the RequestBuilder.
```
$chain = $strict ?
[new AnyOf(new IsInt(), new IsFloat())]
:
[new AnyOf(new AllOf(new ToInt(), new IsInt()), new AllOf(new ToFloat(), new IsFloat());
```
By adding the Number filter/validators it becomes this:
````
$chain = $strict ?
[new IsNumber()]
:
[new ToNumber(), new IsNumber()];
```
> Validator and Filter: IsNumber and ToNumber

- src/OpenAPI/Exception/InvalidOpenAPI.php
- src/OpenAPI/Filter/PathMatcher.php
- src/OpenAPI/PathMatcher.php
- tests/OpenAPI/Filter/PathMatcherTest.php
- tests/OpenAPI/PathMatcherTest.php
OpenAPI/PathMatcher
Helper class designed to return an array of path parameters. 
expects paths to **match exactly from start to finish**
has a `matches($requestPath):bool` method to check if `$requestPath` matches regular expression.
throws Exception if you attempt to `getPathParams($requestPath)` with a path that does not match.
**Example**
```
$sut = new PathMatcher('/pets/{id}');
echo $sut->regex; // #^/pets/(?<id>[^/]+)$#
var_dump($sut->matches('/pets/23')); // (bool) true
var_dump($sut->getPathParams('/pets/23')); // ['id' => '23']
var_dump($sut->matches('/hats/23')); // (bool) false
var_dump($sut->getPathParams('/hats/23')); // This would throw an exception
```
OpenAPI/Filter/PathMatcher
A filter that takes in a string path and returns a result object containing path parameters …
> OpenAPI helper class: PathMatcher added

- composer.json
- src/OpenAPI/Specification/APISchema.php
- src/OpenAPI/Specification/Arrays.php
- src/OpenAPI/Specification/Numeric.php
- src/OpenAPI/Specification/Objects.php
- src/OpenAPI/Specification/Strings.php
- src/OpenAPI/Specification/TrueFalse.php
- tests/OpenAPI/Specification/ArraysTest.php
- tests/OpenAPI/Specification/NumericTest.php
- tests/OpenAPI/Specification/ObjectsTest.php
- tests/OpenAPI/Specification/StringsTest.php
- tests/OpenAPI/Specification/TrueFalseTest.php
`Arrays($fieldName, $schema)` supports schemas with `'type' : 'array'`
`Numeric($fieldName, $schema, $strict = false)` supports schemas with `'type' : 'number'` or `'type' : 'integer'`. 
`$strict` parameter will let NumericBuilder determine if it should use a Filter or stick exclusively to Validators.
`Objects($fieldName, $schema)` supports schemas with `'type' : 'object'`
`Strings($fieldName, $schema)` supports schemas with `'type' : 'string'`
`TrueFalse($fieldName, $schema, $strict = false)` supports schemas with `'type' : 'boolean'`. 
`$strict` parameter will let TrueFalseBuilder determine if it should use a Filter or stick exclusively to Validators.
> OpenAPI Specifications: Type Specific Schema Specifications added

- src/Result/Result.php
- tests/Attribute/BuilderTest.php
Unfortunately my phpstorm settings incorrectly simplified the usage annotations on the AttributeBuilderTest.
This PR reverts them back to correct annotations.
Also simplifies the messageSet annotation on Result.
> Cleanup: Annotation Corrections

- tests/Attribute/BuilderTest.php
- tests/fixtures/Attribute/Docs/BlogPost.php
- tests/fixtures/Attribute/Docs/BlogPostFromNamedArguments.php
- tests/fixtures/Attribute/Docs/BlogPostIsItAString.php
- tests/fixtures/Attribute/Docs/BlogPostMakeItAString.php
- tests/fixtures/Attribute/Docs/BlogPostMaxTags.php
- tests/fixtures/Attribute/Docs/BlogPostRegexAndMaxLength.php
- tests/fixtures/Attribute/Docs/BlogPostWithAllOf.php
RequiredFields attribute originally contained 'tags' like so:
`#[SetFilterOrValidator(new RequiredFields('title', 'body', 'tags'), Placement::BEFORE)]`
'tags' has been removed from each example to better demonstrate that it ignores fields that are not required.
> Doc Test Updates

- src/Validator/FieldSet/RequiredFields.php
- tests/Validator/FieldSet/RequiredFieldsTest.php
Changed fields property to readonly as it is never intended to be written to after construction.
Also small change to naming convention on test arguments to better communicate what is being tested.
> RequiredFields property set to readonly

- docs/validators.md
- src/Validator/FieldSet/FixedFields.php
- tests/Validator/FieldSet/FixedFieldsTest.php
`FixedFields(...$fields)` validates that only fixed fields have been provided. 
This is work towards the Object Builder handling when additionalProperties is set to false.
i.e.
```php
$beforeChain = [];
...
if ($specification->additionalProperties === false) {
$beforeChain[] = new FixedFields(...$specification->properties);
}
...
$beforeSet = new BeforeSet(...$beforeChain)
```
> FixedFields validator added

- docs/processors.md
- src/Exception/InvalidProcessorArguments.php
- src/OpenAPI/Builder/Objects.php
- src/OpenAPI/Specification/Objects.php
- src/Processor/DefaultProcessor.php
- src/Processor/FieldSet.php
- tests/OpenAPI/Builder/ObjectsTest.php
- tests/OpenAPI/Specification/ObjectsTest.php
- tests/Processor/DefaultProcessorTest.php
- tests/Processor/FieldsetTest.php
- add Processor/DefaultProcessor
- refactor FieldSet to handle DefaultProcessor
- add additionalProperties to Object Specification
- add documentation for DefaultProcessor
- fix documentation error on BeforeSet
> Objects Builder handles additionalProperties

- tests/OpenAPI/Builder/RequestBuilderTest.php
Request Builder tests now correctly use the full url including the server.
> Fix test data for Request Builder

- tests/OpenAPI/Processor/RequestTest.php
- tests/Processor/AfterSetTest.php
- tests/Processor/BeforeSetTest.php
- tests/Processor/CollectionTest.php
- tests/Processor/DefaultProcessorTest.php
- tests/Processor/FieldTest.php
- tests/Processor/FieldsetTest.php
Anonymous classes implementing filter and validator interfaces in processor tests have been replaced with existing classes
Problem
When adding new methods to the Validator and Filter interfaces, the Processor tests would explode because their anonymous classes needed to implement the new methods.
Solution
This PR replaces the anonymous classes so that tests do not need refactoring for every change to Validator|Filter interfaces unless it breaks existing behaviour.
Merge before https://github.com/membrane-php/membrane-core/pull/82
> Refactored Processor tests to use existing classes

- src/OpenAPI/PathMatcher.php
This property was specifically the url with the server removed so the name `$serverUrl` was misleading. It is actually the endpoint path so `$pathUrl` seemed more appropriate.
> Reworded PathMatcher property "serverUrl" to "pathUrl"

- src/OpenAPI/Reader/OpenAPIFileReader.php
- src/OpenAPI/Specification/APISpec.php
- src/OpenAPI/Specification/Request.php
- src/OpenAPI/Specification/Response.php
- tests/OpenAPI/Builder/RequestBuilderTest.php
- tests/OpenAPI/Builder/ResponseBuilderTest.php
- tests/OpenAPI/Reader/OpenAPIFileReaderTest.php
- tests/OpenAPI/Specification/APISpecTest.php
- tests/OpenAPI/Specification/RequestTest.php
- tests/OpenAPI/Specification/ResponseTest.php
Adds OpenAPIFileReader:
- has private property of `$supportedFileTypes`
- may be useful if we add a `supports(): bool` method 
- has public method `readFromAbsoluteFilePath(string $absoluteFilePath): OpenApi`
> Moved all OpenAPI file reading to dedicated class

- src/OpenAPI/Exception/CannotReadOpenAPI.php
- src/OpenAPI/Reader/OpenAPIFileReader.php
- tests/OpenAPI/Reader/OpenAPIFileReaderTest.php
**Changes** CannotReadOpenAPI::invalidOpenAPI
```text
'openapi.yaml is not valid OpenAPI'
```
```text
'OpenAPI is invalid due to the following:
- [] OpenApi is missing required property: paths
- [/info] Info is missing required property: title'
```
> Improve CannotReadOpenAPI::invalidOpenAPI Exception

- src/Filter/String/ToPascalCase.php
- tests/Filter/String/ToPascalCaseTest.php
Ensures all words begin with capital letters, characters treated as separators are:
- whitespace
- dash
- underscore
> Add ToPascalCase Filter

- docs/filters.md
- src/Filter/Shape/KeyValueSplit.php
- tests/Filter/Shape/KeyValueSplitTest.php
Takes a list, splits it into two, then combines them to form a key-value array.
- takes a bool arg to specify if keys are first or second. (i.e. even or odd index)
Useful for Objects given in queries.
> Add KeyValueSplit Filter

- bin/membrane
- Adds fallback paths for composer autoloader to ensure it works properly regardless of where the composer bin directory is located 
- Adds support for renamed cli command in router 0.2
> Fixes for CLI command when used as composer package

- composer.json
2.0 was released as of April this year, the only backwards compatible change appears to be that it now requires PHP 7.2.0 or later (which is still well below our minimum requirement).
> Allow psr-http-message ^1.0 || ^2.0

- tests/OpenAPI/ExtractPathParameters/PathMatcherTest.php
assertEquals was allowing one test to pass when it shouldn't have.
Updated to require expected to be identical to actual
> Change PathMatcherTest to assertSame instead of assertEquals

- src/OpenAPI/Builder/OpenAPIRequestBuilder.php
- tests/fixtures/OpenAPI/noReferences.json
The reader checks all parameters contain Schemas xor Content now. 
Membrane core no longer needs to check this
> Remove checks now performed by reader

- docs/validators.md
- src/Validator/String/IntString.php
- tests/Validator/String/IntStringTest.php
Checks a string is an integer, does not accept floats
> Add IntString Validator

- tests/OpenAPI/Builder/StringsTest.php
Fixes a typo from copy pasting tests
> Correct Builder\Strings test name

- src/Membrane.php
- tests/MembraneTest.php
close #128 
Provides static constructor to Membrane to avoid using default builders.
```php
Membrane::withoutDefaults(Builder ...$builders);
```
Behaviour of Membrane via standard construction remains unchanged.
> Membrane without default (merge first)

- src/OpenAPI/Builder/APIBuilder.php
- src/OpenAPI/Builder/Arrays.php
- src/OpenAPI/Builder/Objects.php
- src/OpenAPI/Builder/OpenAPIRequestBuilder.php
- src/OpenAPI/Builder/ParameterBuilder.php
- src/OpenAPI/Exception/CannotProcessOpenAPI.php
- src/OpenAPI/Specification/Arrays.php
- src/OpenAPI/Specification/Objects.php
- src/OpenAPI/Specification/OpenAPIRequest.php
- src/OpenAPI/Specification/OpenAPIResponse.php
- src/OpenAPI/Specification/Parameter.php
- tests/Console/Command/CacheOpenAPIProcessorsTest.php
- tests/Console/Service/CacheOpenAPIProcessorsTest.php
- tests/OpenAPI/Builder/OpenAPIRequestBuilderTest.php
- tests/OpenAPI/Builder/ParameterBuilderTest.php
- tests/OpenAPI/Builder/RequestBuilderTest.php
- tests/OpenAPI/Specification/OpenAPIRequestTest.php
- tests/OpenAPI/Specification/OpenAPIResponseTest.php
- tests/OpenAPI/Specification/ParameterTest.php
- tests/fixtures/OpenAPI/docs/petstore-expanded.json
- tests/fixtures/OpenAPI/docs/petstore.yaml
- tests/fixtures/OpenAPI/hatstore.json
close #60 
Currently throws exceptions for the petstore examples (since they have default query style of form, with explode:true
> Handle style (merge second)

- src/OpenAPI/Filter/QueryStringToArray.php
- tests/OpenAPI/Filter/QueryStringToArrayTest.php
This filter 
1. explodes on `&` into _segments._ 
2. explodes each value on `=` into _pairs._
3. inserts each _pair_ as a key-value pair into an array (without overwriting)
The result is an `array<string,string[]>`
See the test for example outputs.
What this does is handle collecting the data together based on properties, **after which** it will still need to handle the style elsewhere. This can be added to the beforeSet for query parameters, something in each field processor will need to handle individual styles.
A combination of differing styles and explodes should not cause issue referring to this:
https://github.com/OAI/OpenAPI-Specification/issues/1508
> Add QueryStringToArray Filter

- src/OpenAPI/Builder/APIBuilder.php
- src/OpenAPI/Exception/CannotProcessOpenAPI.php
- tests/OpenAPI/Builder/ObjectsTest.php
- tests/OpenAPI/Builder/OpenAPIRequestBuilderTest.php
- tests/OpenAPI/Builder/OpenAPIResponseBuilderTest.php
- tests/OpenAPI/Builder/ResponseBuilderTest.php
close #135 
subschemas within AnyOf|AllOf|OneOf will have the sub-schema's title if available or fallback to 'Branch 1', 'Branch 2' etc.
Refactors all complex schemas to use same method.
Adds a conditional check for empty complex schemas which are technically valid but completely pointless.
> Complex schema message branches

- src/Validator/String/Length.php
- tests/Validator/String/LengthTest.php
Closes #171
Use mb_strlen instead of strlen to avoid multibyte characters being considered as more than 1.
> Fix String\Length Validator for multibyte chararacters

- composer.json
- src/Filter/Type/NullOr.php
- tests/Filter/Type/NullOrTest.php
- tests/fixtures/Filter/ToThis.php
Wraps another filter, accepts null or defers to wrapped filter. 
Useful for nullable properties.
Also adds `ToThis` filter for testing purposes. Ignores whatever value it is passed and returns itself as the `Result` `value`.
> Add NullOr Filter
